source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.3'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.7'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer', :platform => :ruby
gem 'execjs'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'bcrypt', '~> 3.1.7', :platform => :ruby
gem 'dalli'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'thin'
end

# Refinery CMS
gem 'refinerycms', '~> 4.0'

# Optionally, specify additional Refinery CMS Extensions here:
gem 'refinerycms-acts-as-indexed', ['~> 3.0', '>= 3.0.0']
gem 'refinerycms-wymeditor', ['~> 2.0', '>= 2.0.0']
gem 'refinerycms-authentication-devise', '~> 2.0'
#gem 'refinerycms-blog', ['~> 4.0', '>= 4.0.0']
#gem 'refinerycms-inquiries', ['~> 4.0', '>= 4.0.0']
#gem 'refinerycms-search', ['~> 4.0', '>= 4.0.0']
#gem 'refinerycms-page-images', ['~> 4.0', '>= 4.0.0']
gem 'refinerycms-page-images', '~> 4.0.0', git: "https://github.com/refinery/refinerycms-page-images", branch: "master"

gem 'refinerycms-settings'

gem 'refinerycms-pv_board_directors', path: 'vendor/extensions'
gem 'refinerycms-pv_categories', path: 'vendor/extensions'
gem 'refinerycms-pv_bulletins', path: 'vendor/extensions'
gem 'refinerycms-pv_documents', path: 'vendor/extensions'
gem 'refinerycms-pv_faqs', path: 'vendor/extensions'
gem 'refinerycms-pv_home_main_sections', path: 'vendor/extensions'


gem 'refinerycms-pv_stocks', path: 'vendor/extensions'

gem 'refinerycms-pv_interest_links', path: 'vendor/extensions'
gem 'refinerycms-pv_emissions', path: 'vendor/extensions'
gem 'refinerycms-pv_doc_emissions', path: 'vendor/extensions'
gem 'refinerycms-pv_services', path: 'vendor/extensions'
gem 'refinerycms-pv_slider_images', path: 'vendor/extensions'